<?php
echo $this->extend('default');
echo $this->section('content');

$default = [
    'start_time' => htmlDatetimeLocal('now'),
    'end_time'   => htmlDatetimeLocal('+1 hour'),
];
?>

<style>
html, body { height: 100%; margin: 0; padding: 0; overflow: hidden; }
header, footer { display: none; }
#map { position: fixed; inset: 0; z-index: 0; }
#map-time-panel {
    position: fixed;
    bottom: 20px;
    right: 10px;
    z-index: 1000;
    background: white;
    padding: 12px 16px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.3);
    width: 280px;
}
#map-time-panel .col-sm-4 {
    width: 100%;
    max-width: 100%;
    flex: 0 0 100%;
}
</style>

<link rel="stylesheet"
      href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
      integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
      crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>

<!-- locate control plugin -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.84.2/dist/L.Control.Locate.min.css" />
<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.84.2/dist/L.Control.Locate.min.js" charset="utf-8"></script>

<!-- easy button plugin -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.css">
<script src="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.js"></script>

<div id="map"></div>

<script src="/assets/js/map_route.js"></script>

<div id="map-time-panel">
    <?php echo formInputBootstrap('start_time', 'Start Time', value: $default['start_time'], type: 'datetime-local'); ?>
    <?php echo formInputBootstrap('end_time', 'End Time', value: $default['end_time'], type: 'datetime-local'); ?>
</div>

<script>
function haversineDistance(lat1, lon1, lat2, lon2) {
    const R = 6371000;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function downloadGpx() {
    const route = loadRoute();
    if (route.length === 0) return;

    const startTime = new Date(document.getElementById('start_time').value);
    const endTime   = new Date(document.getElementById('end_time').value);
    const duration  = (endTime - startTime) / 1000;
    const first     = route[0];
    const last      = route[route.length - 1];
    const totalDist = haversineDistance(first[0], first[1], last[0], last[1]);
    const speed     = totalDist > 0 && duration > 0 ? totalDist / duration : 0;

    const trackpoints = route.map(([lat, lon, ele = 0]) => {
        const dist = haversineDistance(first[0], first[1], lat, lon);
        const t    = new Date(startTime.getTime() + (speed > 0 ? dist / speed : 0) * 1000);
        return `      <trkpt lat="${lat}" lon="${lon}"><ele>${ele}</ele><time>${t.toISOString()}</time></trkpt>`;
    }).join('\n');

    const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="MaxFlow tools">
  <trk>
    <name>Route generated by MaxFlow tools</name>
    <type>RUN</type>
    <trkseg>
${trackpoints}
    </trkseg>
  </trk>
</gpx>`;

    const date    = new Date().toISOString().split('T')[0];
    const element = document.createElement('a');
    element.setAttribute('href', 'data:application/gpx+xml;charset=utf-8,' + encodeURIComponent(gpx));
    element.setAttribute('download', `maxflow-${date}.gpx`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
}
</script>

<?php echo $this->endSection(); ?>
