<?php

namespace App\Controllers;

use App\Helpers\Logger;
use CodeIgniter\HTTP\DownloadResponse;
use phpGPX\Helpers\GeoHelper;
use phpGPX\Models\GpxFile;
use phpGPX\Models\Point;
use phpGPX\Models\Segment;
use phpGPX\Models\Track;

class ToolGeo extends BaseController
{
    public function viewMapRoute(): string
    {
        return $this->loadView();
    }

    /**
     * Handle request from map route.
     */
    public function handleMapRoute(): string|DownloadResponse|null
    {
        $post = (array) $this->request->getPost();
        Logger::debug('post data ', $post);

        $rules = [
            'geojson' => 'required',
            'start_time' => 'valid_date',
            'end_time' => 'valid_date',
        ];

        if (! $this->validateData($post, $rules)) {
            return $this->loadView();
        }

        $content = json_decode((string) $post['geojson'], true);
        $coords = $content['geometry']['coordinates'];

        $gpx = $this->createGpx($coords, startTime: $post['start_time'], endTime: $post['end_time']);
        Logger::debug('Result is ', $gpx);

        $date = \Carbon\Carbon::now()->format('Y-m-d');
        $filename = sprintf('maxflow-%s.gpx', $date);

        return $this->response->download($filename, $gpx);
    }

    /**
     * @param array<array{float, float, ?float}> $points
     * @param array<string, string>              $params
     */
    private function createGpx(array $points, string $startTime, string $endTime, array $params = []): string
    {
        $gpxFile = new GpxFile();

        $track = new Track();
        $track->name = 'Route generated by MaxFlow tools';
        $track->type = $params['type'] ?? 'RUN';

        $startTime = \Carbon\Carbon::parse($startTime)->getTimestamp();
        $duration = \Carbon\Carbon::parse($endTime)->getTimestamp() - $startTime;

        $segment = new Segment();
        foreach ($points as $p) {
            $point = new Point(Point::TRACKPOINT);
            $point->latitude = $p[0];
            $point->longitude = $p[1];
            $point->elevation = $p[2] ?? 0;
            $segment->points[] = $point;
        }

        // Length of the segment.
        $lastPoint = end($segment->points);
        assert(false != $lastPoint);
        $firstPoint = $segment->points[0];

        $segmentLength = GeoHelper::getRealDistance($firstPoint, $lastPoint);
        $speed = floatval($segmentLength) / floatval($duration);
        Logger::info('Segment length %s m for duration %d sec, speed=%s m/s', $segmentLength, $duration, $speed);

        // add timestamp.
        foreach ($segment->points as &$point) {
            $distance = GeoHelper::getRawDistance($firstPoint, $point);
            $dtInSec = $speed * $distance;
            $time = \Carbon\Carbon::now()->setTimestamp(intval($startTime + $dtInSec));
            $point->time = $time;
        }

        $track->segments[] = $segment;
        $track->recalculateStats();
        $gpxFile->tracks[] = $track;

        return (string) $gpxFile->toXML()->saveXML();
    }

    /**
     * @param array<string, mixed> $extra
     */
    private function loadView(array $extra = []): string
    {
        $post = (array) $this->request->getPost();
        $data = [...$post, ...$extra];

        return view('tools/map_route', $data);
    }
}
